
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Dec 22 12:56:05 CET 2021
//----------------------------------------------------

package compiler.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONT = 30;
  public static final int CONST = 5;
  public static final int CHAR = 23;
  public static final int GRT = 36;
  public static final int LPAREN = 15;
  public static final int SEMI = 6;
  public static final int MINUS = 46;
  public static final int RPAREN = 16;
  public static final int GRE = 37;
  public static final int AND = 40;
  public static final int RECORD = 12;
  public static final int EXTND = 14;
  public static final int COLUMN = 8;
  public static final int OR = 41;
  public static final int BOOL = 21;
  public static final int COMMA = 7;
  public static final int CLASS = 13;
  public static final int INC = 47;
  public static final int DIV = 43;
  public static final int PLUS = 45;
  public static final int IF = 24;
  public static final int DOT = 17;
  public static final int EOF = 0;
  public static final int RETURN = 31;
  public static final int EQUAL = 9;
  public static final int NEW = 19;
  public static final int error = 1;
  public static final int MUL = 42;
  public static final int MOD = 44;
  public static final int NUMBER = 20;
  public static final int NEQ = 35;
  public static final int BREAK = 29;
  public static final int IDENT = 22;
  public static final int VOID = 18;
  public static final int LBRACK = 10;
  public static final int EQU = 34;
  public static final int LBRACE = 3;
  public static final int ELSE = 25;
  public static final int READ = 32;
  public static final int RBRACK = 11;
  public static final int GOTO = 26;
  public static final int WHILE = 28;
  public static final int LES = 38;
  public static final int RBRACE = 4;
  public static final int PROG = 2;
  public static final int DEC = 48;
  public static final int LEE = 39;
  public static final int PRINT = 33;
  public static final int DO = 27;
}

